version: '3.8'

services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_DOCKER_URI}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  mongo:
    container_name: mongo
    image: docker.arvancloud.ir/mongo
    volumes:
      - ./mongodata:/data/mongo
    ports:
      - '27017:27017'
    networks:
      - backend

  redis:
    image: docker.arvancloud.ir/redis:7.4.2
    container_name: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodata: {}
  app: {}
